name: example
description: Stater demo project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  state_mgr: ^1.0.1
  state_mgr:
    path: d:/Users/Aleks/flutter/state_mgr/

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
